services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: "backend.env"

  ci:
    image: node:22-alpine
    ports:
      - "1337:1337"
    volumes:
      - .:/app
    working_dir: /app
    env_file: "backend.env"
    command: yarn start
