services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: "backend.env"
    networks:
      - backend

  ci:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    working_dir: /app
    env_file: "backend.env"
    networks:
      - backend

networks:
  backend:
    driver: bridge
