// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { ProductsId } from './Products';

/** Represents the table public.cart_items */
export default interface CartItems {
  user_id: UsersId;

  product_id: ProductsId;

  quantity: number;
}

/** Represents the initializer for the table public.cart_items */
export interface CartItemsInitializer {
  user_id: UsersId;

  product_id: ProductsId;

  quantity: number;
}

/** Represents the mutator for the table public.cart_items */
export interface CartItemsMutator {
  user_id?: UsersId;

  product_id?: ProductsId;

  quantity?: number;
}
