// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.categories */
export type CategoriesId = number & { __brand: 'CategoriesId' };

/** Represents the table public.categories */
export default interface Categories {
  id: CategoriesId;

  name: string;
}

/** Represents the initializer for the table public.categories */
export interface CategoriesInitializer {
  /** Default value: nextval('categories_id_seq'::regclass) */
  id?: CategoriesId;

  name: string;
}

/** Represents the mutator for the table public.categories */
export interface CategoriesMutator {
  id?: CategoriesId;

  name?: string;
}
