// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.metadata */
export type MetadataKey = string & { __brand: 'MetadataKey' };

/** Represents the table public.metadata */
export default interface Metadata {
  key: MetadataKey;

  value: string;
}

/** Represents the initializer for the table public.metadata */
export interface MetadataInitializer {
  key: MetadataKey;

  value: string;
}

/** Represents the mutator for the table public.metadata */
export interface MetadataMutator {
  key?: MetadataKey;

  value?: string;
}
