// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.orders */
export type OrdersId = number & { __brand: 'OrdersId' };

/** Represents the table public.orders */
export default interface Orders {
  id: OrdersId;

  user_id: UsersId;

  created_at: Date;
}

/** Represents the initializer for the table public.orders */
export interface OrdersInitializer {
  /** Default value: nextval('orders_id_seq'::regclass) */
  id?: OrdersId;

  user_id: UsersId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.orders */
export interface OrdersMutator {
  id?: OrdersId;

  user_id?: UsersId;

  created_at?: Date;
}
