// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProductsId } from './Products';
import type { UsersId } from './Users';

/** Represents the table public.reviews */
export default interface Reviews {
  product_id: ProductsId;

  user_id: UsersId;

  rating: number;

  created_at: Date;

  comment: string | null;
}

/** Represents the initializer for the table public.reviews */
export interface ReviewsInitializer {
  product_id: ProductsId;

  user_id: UsersId;

  rating: number;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  comment?: string | null;
}

/** Represents the mutator for the table public.reviews */
export interface ReviewsMutator {
  product_id?: ProductsId;

  user_id?: UsersId;

  rating?: number;

  created_at?: Date;

  comment?: string | null;
}
