// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProductsId } from './Products';
import type { UsersId } from './Users';

/** Identifier type for public.reviews */
export type ReviewsId = number & { __brand: 'ReviewsId' };

/** Represents the table public.reviews */
export default interface Reviews {
  id: ReviewsId;

  product_id: ProductsId;

  user_id: UsersId;

  rating: number;

  created_at: Date;

  comment: string | null;
}

/** Represents the initializer for the table public.reviews */
export interface ReviewsInitializer {
  /** Default value: nextval('reviews_id_seq'::regclass) */
  id?: ReviewsId;

  product_id: ProductsId;

  user_id: UsersId;

  rating: number;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  comment?: string | null;
}

/** Represents the mutator for the table public.reviews */
export interface ReviewsMutator {
  id?: ReviewsId;

  product_id?: ProductsId;

  user_id?: UsersId;

  rating?: number;

  created_at?: Date;

  comment?: string | null;
}
