name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive

    - name: Verify docker is installed
      id: docker-version
      continue-on-error: true
      run: docker --version

    - name: Verify docker-compose is installed
      id: docker-compose-version
      continue-on-error: true
      run: docker compose --version

    - name: Install docker / docker-compose
      if: steps.docker-version.outcome == 'failure' || steps.docker-compose-version.outcome == 'failure'
      run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-compose-plugin

    - name: Start Docker
      run: |
          sudo service docker start
          sudo docker ps

    - name: Start service db and ci
      run: docker compose -f docker-compose.yml up -d db ci

    - name: Wait until webserver is ready
      timeout-minutes: 1
      id: wait
      continue-on-error: true
      run: |
          sudo netstat -tulpn
          curl -s http://localhost:1337/healthz --retry 10 --retry-connrefused --retry-delay 5 --retry-max-time 60 -vvv
          #while ! curl -s http://localhost:1337/healthz; do
          #    sleep 1
          #done
    - name: Get container logs if failed
      if: steps.wait.outcome == 'failure'
      run: |
        docker compose -f docker-compose.yml logs
        exit 1

    - name: Run Playwright tests from commanderred42/webstore-playwright
      run: docker run --rm -v $PWD/playwright-report:/playwright-report --network="host" commanderred42/webstore-playwright

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
